name: Daily Workflow

on:
  schedule:
    - cron: '31 21 * * *'  # This means the action will run every day at 6 AM UTC (2 AM EST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace with the version of Python you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Utest
      run: python run_Utest.py

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test_results.txt

    - name: Download test results
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: ./test_results.txt

    - name: Email Utest
      env:
        API_KEY: ${{ secrets.API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python email_Utest.py
